# -*- coding: utf-8 -*-
"""MoneyWise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auPAl4xKomz2xBlGgZV94wpIEMh5OG3W

**Фінансовий консультант "MoneyWise"**
"""

!pip install -qU --no-warn-conflicts "langchain<0.3.0" "langchain-community<0.3.0" "langchain-core<0.3.0" "langchain-google-genai" requests

import os
import math
import logging
import requests
from typing import Optional

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.agents import AgentExecutor, create_react_agent
from langchain_core.tools import tool
from langchain_core.prompts import PromptTemplate
from langchain.memory import ConversationBufferWindowMemory

# 1. Налаштування API
try:
    from google.colab import userdata
    os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')
except ImportError:
    from getpass import getpass
    if "GOOGLE_API_KEY" not in os.environ:
        os.environ["GOOGLE_API_KEY"] = getpass("Введіть ваш Google Gemini API Key: ")

# 2. Налаштування логування
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [MoneyWise] - %(message)s')
logger = logging.getLogger(__name__)

llm = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite", temperature=0)

# ==========================================
# 3. ІНСТРУМЕНТИ
# ==========================================

@tool
def currency_converter(params: str) -> str:
    """Конвертує валюти.
    Action Input має бути рядком, де значення розділені комою: сума, з_якої_валюти, в_яку_валюту.
    Приклад Action Input: 2500, USD, UAH
    """
    logger.info(f"currency_converter отримав: {params}")
    try:
        # Розпаковуємо рядок на змінні
        parts = [p.strip() for p in params.split(',')]
        amount = float(parts[0])
        from_currency = parts[1].upper()
        to_currency = parts[2].upper()

        if amount <= 0: return "Помилка: сума повинна бути більшою за нуль."
        response = requests.get(f"https://api.exchangerate-api.com/v4/latest/{from_currency}", timeout=5)
        response.raise_for_status()
        rate = response.json()['rates'].get(to_currency)
        if not rate: return f"Помилка: Валюту {to_currency} не знайдено."
        return f"✅ {amount} {from_currency} = {amount * rate:.2f} {to_currency} (Курс: {rate})"
    except Exception as e:
        return f"Помилка при конвертації (перевірте формат даних): {str(e)}"

@tool
def loan_calculator(params: str) -> str:
    """Розраховує кредит.
    Action Input має бути рядком (через кому): сума, річна_ставка, місяці, тип(ануїтет або диференційований).
    Приклад Action Input: 100000, 20, 24, ануїтет
    """
    logger.info(f"loan_calculator отримав: {params}")
    try:
        parts = [p.strip() for p in params.split(',')]
        principal = float(parts[0])
        annual_rate = float(parts[1])
        months = int(parts[2])
        loan_type = parts[3].lower() if len(parts) > 3 else "ануїтет"

        if principal <= 0 or annual_rate < 0 or months <= 0: return "Помилка валідації."
        monthly_rate = annual_rate / 100 / 12
        if "ануїтет" in loan_type:
            payment = principal / months if monthly_rate == 0 else principal * (monthly_rate * (1 + monthly_rate)**months) / ((1 + monthly_rate)**months - 1)
            return f"💰 Ануїтет:\n- Платіж: {payment:.2f} грн\n- Переплата: {(payment * months) - principal:.2f} грн"
        elif "диференційован" in loan_type:
            pr_payment = principal / months
            return f"💰 Диференційований:\n- Перший платіж: {pr_payment + principal * monthly_rate:.2f} грн\n- Останній: {pr_payment + pr_payment * monthly_rate:.2f} грн"
        return "Невідомий тип кредиту."
    except Exception as e:
        return f"Помилка розрахунку кредиту: {str(e)}"

@tool
def savings_goal(params: str) -> str:
    """Розраховує план накопичення на мету.
    Action Input має бути рядком (через кому): цільова_сума, щомісячний_внесок, кількість_місяців, річна_ставка.
    Якщо якогось параметра немає, вкажіть 0.
    Приклад Action Input: 300000, 5000, 0, 0
    """
    logger.info(f"savings_goal отримав: {params}")
    try:
        parts = [p.strip() for p in params.split(',')]
        target_amount = float(parts[0])
        monthly_savings = float(parts[1]) if len(parts) > 1 else 0
        months_available = int(parts[2]) if len(parts) > 2 else 0
        annual_return = float(parts[3]) if len(parts) > 3 else 0

        monthly_return = annual_return / 100 / 12 if annual_return > 0 else 0
        if monthly_savings > 0 and months_available == 0:
            m_needed = target_amount / monthly_savings if monthly_return == 0 else math.log(1 + target_amount * monthly_return / monthly_savings) / math.log(1 + monthly_return)
            return f"🎯 Накопичите за {int(m_needed // 12)} років та {int(math.ceil(m_needed % 12))} місяців."
        elif months_available > 0 and monthly_savings == 0:
            req_monthly = target_amount / months_available if monthly_return == 0 else target_amount * monthly_return / ((1 + monthly_return)**months_available - 1)
            return f"🎯 Потрібно відкладати {req_monthly:.2f} грн щомісяця."
        return "Вкажіть АБО суму внеску, АБО термін (не обидва)."
    except Exception as e:
        return f"Помилка планування: {str(e)}"

@tool
def budget_analyzer(params: str) -> str:
    """Аналізує витрати за правилом 50/30/20.
    Action Input має бути рядком (через кому): дохід, витрати_на_житло, їжа, транспорт, інші_витрати.
    Приклад Action Input: 50000, 15000, 8000, 2000, 10000
    """
    logger.info(f"budget_analyzer отримав: {params}")
    try:
        parts = [p.strip() for p in params.split(',')]
        income = float(parts[0])
        housing = float(parts[1])
        food = float(parts[2])
        transport = float(parts[3])
        others = float(parts[4])

        needs_pct = ((housing + food + transport) / income) * 100
        wants_pct = (others / income) * 100
        savings_pct = ((income - (housing + food + transport + others)) / income) * 100
        ans = f"📊 Бюджет (50/30/20):\n- Потреби: {needs_pct:.1f}% (Норма: 50%)\n- Бажання: {wants_pct:.1f}% (Норма: 30%)\n- Заощадження: {savings_pct:.1f}% (Норма: 20%)\n"
        if needs_pct > 50: ans += "⚠️ Базові витрати зависокі.\n"
        if savings_pct < 0: ans += "🚨 КРИТИЧНО: Витрати перевищують дохід!"
        return ans
    except Exception as e:
        return f"Помилка аналізу: {str(e)}"

tools = [currency_converter, loan_calculator, savings_goal, budget_analyzer]

# ==========================================
# 4. АГЕНТ ТА ПАМ'ЯТЬ
# ==========================================

system_template = """Ти — аналітичний фінансовий консультант "MoneyWise".
Твоя мета — допомагати з розрахунками.
1. ЗАВЖДИ використовуй інструменти для математики.
2. В кінці відповіді додавай: "Зверніть увагу: бот надає лише інформаційну підтримку і не є заміною професійної фінансової консультації."
Якщо користувач вітається, привітайся у відповідь без використання інструментів.

Доступні інструменти:
{tools}

Щоб використати інструмент, СУВОРО дотримуйся цього формату:
Thought: роздуми про те, який інструмент потрібен
Action: назва інструменту (одна з: {tool_names})
Action Input: значення1, значення2, значення3 (лише рядок зі значеннями через кому!)
Observation: результат інструменту
... (може повторюватися)
Thought: знаю відповідь
Final Answer: фінальна відповідь

Історія діалогу:
{chat_history}

Питання: {input}
Thought:{agent_scratchpad}"""

prompt = PromptTemplate.from_template(system_template)
memory = ConversationBufferWindowMemory(k=5, memory_key="chat_history", return_messages=False)

agent = create_react_agent(llm, tools, prompt)
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    memory=memory,
    verbose=False,
    handle_parsing_errors="Будь ласка, переконайся, що Action Input передається як один рядок зі значеннями через кому.",
    max_iterations=20
)

# ==========================================
# 5. ІНТЕРФЕЙС
# ==========================================

def start_chat():
    print("="*60)
    print("🤖 Вітаємо! Я — фінансовий консультант MoneyWise.")
    print("Команди: 'вихід' (завершити), 'скинути' (очистити історію).")
    print("="*60)

    while True:
        user_input = input("\nВи: ").strip()

        if user_input.lower() in ['вихід', 'exit']:
            print("MoneyWise: До побачення!")
            break
        if user_input.lower() in ['скинути']:
            memory.clear()
            print("MoneyWise: 🔄 Контекст очищено.")
            continue
        if not user_input: continue

        try:
            logger.info(f"Запит: {user_input}")
            response = agent_executor.invoke({"input": user_input})
            print(f"\nMoneyWise: {response['output']}")
        except Exception as e:
            print(f"\n❌ Системна помилка: {str(e)}")

if __name__ == "__main__":
    start_chat()

import time

# Список тестових запитів, які покривають усі вимоги завдання
test_queries = [
    # 1. Тест інструменту currency_converter
    "Скільки буде 1000 доларів у гривнях?",

    # 2. Тест пам'яті (контексту)
    "А якщо цю ж суму перевести у євро?",

    # 3. Тест інструменту loan_calculator (ануїтет)
    "Розрахуй кредит: 100000 грн, 20% річних, на 2 роки. Тип - ануїтет.",

    # 4. Тест пам'яті та зміни параметрів (диференційований)
    "Перерахуй цей же кредит, але зроби тип платежу диференційованим.",

    # 5. Тест інструменту savings_goal (розрахунок часу)
    "За скільки я накопичу на машину за 300000 грн, якщо відкладатиму 5000 на місяць?",

    # 6. Тест інструменту savings_goal (розрахунок суми з контексту)
    "А скільки треба відкладати щомісяця, щоб накопичити ці 300000 грн за 2 роки?",

    # 7. Тест інструменту budget_analyzer
    "Проаналізуй мої витрати: дохід 50000, житло 15000, їжа 10000, транспорт 5000, інші витрати 15000.",

    # 8. Тест обробки помилок (негативна сума)
    "Конвертуй -500 доларів у гривні.",

    # 9. Тест обробки помилок у калькуляторі кредитів
    "Розрахуй кредит на 10000 грн під 15% річних на 0 місяців.",

    # 10. Тест обмежень системного промпту (дисклеймер)
    "Які акції технологічних компаній порадите купити просто зараз для максимального прибутку?"
]

def run_automated_tests():
    print("="*60)
    print("🚀 СТАРТ АВТОМАТИЗОВАНОГО ТЕСТУВАННЯ АГЕНТА MoneyWise")
    print("="*60)

    # Переконуємося, що пам'ять чиста перед початком тестів
    memory.clear()

    for i, query in enumerate(test_queries, 1):
        print(f"\n[{i}/11] 🧑‍💻 Користувач: {query}")
        print("-" * 40)

        try:
            # invoke викликає агента, передаючи йому запит та історію
            response = agent_executor.invoke({"input": query})
            print(f"🤖 MoneyWise: {response['output']}\n")
        except Exception as e:
            print(f"❌ Помилка виконання: {str(e)}\n")

        # Пауза 2 секунди, щоб не перевищити ліміти API безкоштовного рівня
        time.sleep(2)

    # 11. Тест очищення пам'яті
    print(f"\n[11/11] 🔄 Очищення пам'яті та перевірка контексту...")
    memory.clear()
    final_test = "Про яку суму кредиту ми говорили в попередніх повідомленнях?"
    print(f"🧑‍💻 Користувач: {final_test}")
    print("-" * 40)
    response = agent_executor.invoke({"input": final_test})
    print(f"🤖 MoneyWise: {response['output']}\n")

    print("="*60)
    print("✅ ТЕСТУВАННЯ ЗАВЕРШЕНО")
    print("="*60)

# Запуск тестів
run_automated_tests()